version: "3"

services:
  db:
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=home-flex
    ports:
      - "5432:5432"
    volumes:
      - db_data:/bitnami/postgresql

volumes:
  db_data:
    driver: local
