export enum ErrorsEnum {
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USER_ENTERPRISE_NOT_FOUND = 'USER_ENTERPRISE_NOT_FOUND',

  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
